<?php

namespace AppBundle\Repository;

/**
 * ShareholderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareholderRepository extends \Doctrine\ORM\EntityRepository
{
}
